trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: echo Build First Job
      - bash: echo $(System.DefaultWorkingDirectory)
      - bash: ls -r  $(System.DefaultWorkingDirectory)
      - bash: echo $(Build.ArtifactStagingDirectory)
      - bash: ls -r  $(Build.ArtifactStagingDirectory)