
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
    - job: firstjob
      steps:
      - bash: echo Build First Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
    - job: DevFist
      steps:
      - bash: echo Dev First Job
- stage: QADeploy
  dependsOn: Build
  jobs:
    - job: QAJob
      steps:
      - bash: echo QA First Job
- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
    - job: ProductionsJob
      steps:
      - bash: echo Production First Job